remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Arailym Mussilim
description: Hi there! Please take a look at my data analyst portfolio and do not hesitate to reach out to me at @arailym.mussilim@mail.utoronto.ca
show_downloads: false
google_analytics: true
